### PR TITLE
Remove Cyclic Complexity

### PR DESCRIPTION
**Pull request by DonkeyCo**
Just removed some if statements to reduce cyclic complexity for the blog entry.

### CODE REVIEW

**Comment by JoschuaGoetz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ fridgify_backend/views/fridge/management/users/management.py  3
         

Coverage decreased per file
===========================
- fridgify_backend/utils/decorators.py  -1
         

Complexity decreasing per file
==============================
+ fridgify_backend/views/users/users_duplicate.py  -5
+ fridgify_backend/views/fridge/management/users/management.py  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Fridgify/Fridgify_Backend/pullRequest?prid=5648017&bid=18495941)

**Comment by JoschuaGoetz** [comment]
Im sorry that i abuse your PR to update the codacy badges. But well i did

**Comment by JoschuaGoetz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ fridgify_backend/views/fridge/management/users/management.py  3
         

Coverage decreased per file
===========================
- fridgify_backend/utils/decorators.py  -1
         

Complexity decreasing per file
==============================
+ fridgify_backend/views/fridge/management/users/management.py  -4
+ fridgify_backend/views/users/users_duplicate.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Fridgify/Fridgify_Backend/pullRequest?prid=5648017&bid=18495941)

**Comment by DonkeyCo** [comment]
No biggie

**Pull request merged**
