### PR TITLE
Add codacy badge

### PR DESCRIPTION
**Pull request by JoschuaGoetz**

### CODE REVIEW

**Comment by DonkeyCo** [comment]
You could also think about adding a Coverage Badge from Codacy, instead of using the one in the folder with a relative path, to make the README readable in DockerHub
[Codacy Badge](https://www.codacy.com/gh/Fridgify/Fridgify_Backend?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=Fridgify/Fridgify_Backend&amp;utm_campaign=Badge_Coverage)

**Comment by JoschuaGoetz** [comment]
Yeah that would be a good idea. I didnt add it here because it doesnt seem to work. My guess is that it only takes the coverage in the master branch. Lets check that if we release another version.

**Comment by DonkeyCo** [comment]
It seems like you can make an API call to choose a coverage badge for a specific branch:
https://api.codacy.com/project/badge/Grade/a0000?branch=test
https://app.codacy.com/project/badge/Coverage/a12a694e4db141db8ad32441a7a89dce?branch=develop

https://support.codacy.com/hc/en-us/articles/212799365-Badges

**Comment by JoschuaGoetz** [comment]
Oh great I will play around with that

**Comment by JoschuaGoetz** [comment]
@fridgify-build rest in peace. We will never forget the countless commit messages. "Update coverage badge". So iconic.

**Comment by JoschuaGoetz** [comment]
I added protobuf because its a dependency of something else and it couldnt be loaded. It complained about not finding the version but when i added it manually it found the version. Pure magic

**Comment by JoschuaGoetz** [comment]
Im confused as why protobuff is now installing, but well. It should work now

**Pull request merged**
