### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by DonkeyCo**
This pull request is pretty big, I know. I tried to refactor the backend after running pylint. If you see any mistake, do not hesitate to tell me.

### CODE REVIEW

**Comment by DonkeyCo** [comment]
Seems like there is something wrong with Codacy. I don't understand why it cannot review the PR. Could you have a look at it @JoschuaGoetz ?

**Comment by JoschuaGoetz** [comment]
Seems like you have to manually select each branch you work on. It ust selected now. Do you have something you want to change ? A new commit could trigger an update

**Comment by JoschuaGoetz** [comment]
Never mind i can restart the report. I check whats up with it

**Comment by JoschuaGoetz** [comment]
This seems to be an issue with codacy itself. At least the coverage reporter has an open issue i [commented](https://github.com/codacy/codacy-coverage-reporter/issues/226#issuecomment-636454866) on. But the PR report isnt working either. I check with an PR on the frontend and we have the same issue there. I even get an internal server error when trying to view the difference on this PR. image

I guess we have to disable PR analysis until this is resolved. I check if i can file an issue somewhere on codacy

**Comment by JoschuaGoetz** [comment]
https://support.codacy.com/hc/en-us/requests/10715

**Comment by DonkeyCo** [comment]
I can't open up the link, but I guess you are the only one, who is able to look into the support request

**Pull request merged**
