### PR TITLE
API v1.1

### PR DESCRIPTION
**Pull request by DonkeyCo**
The **new** API version contains the following changes:

- a *documentation* which is on **fridgapi.donkz.dev** or (if you are on dev landscape: **fridgapi-dev.donkz.dev**)
- a complete refactoring of the code, using **Django's** and **Django Rest Framework's** best practices (e.g. api_view decorator, Serializers, etc.)
- cleaned up code base to avoid redundancy

### CODE REVIEW

**Comment by DonkeyCo** [comment]
@JoschuaGoetz Could you please have a look at the changes? If there is anything we can change, don't hesitate to mention it.

**Comment by DonkeyCo** [comment]
Yeah. I'm currently working on it. It seems like there are problems with serving a) the static files and b) I may have to look into disabling the login option. I will @ you when, everything works fine

**Comment by JoschuaGoetz** [comment]
Alright, hit me up if you need help.

**Comment by DonkeyCo** [comment]
@JoschuaGoetz Should be all good now. Could you check if it is working correctly?
To solve the static files problem, I had to create a volume which points to a static folder in the docker container and mounts to a host folder. I point to this folder in the NGINX configuration. I did the changes in the Develop Dockerfile as well as in the Production Dockerfile.

**Comment by JoschuaGoetz** [comment]
Works like a charm. Great work

**Pull request merged**
